"use client";
import Link from "next/link";
import Navbar from "../Navbar/Navbar";
import { useState, useEffect } from "react";

// keepng the sample transactions hard coded for now
const sampleTransactions = [
	{
		account_id: "nGkKy41bepIEz8v7X3Axho6QnbV5pDHAl7ggK",
		account_owner: null,
		amount: 25,
		authorized_date: "2024-11-19",
		authorized_datetime: null,
		category: ["Payment", "Credit Card"],
		category_id: "16001000",
		check_number: null,
		counterparties: [],
		date: "2024-11-20",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "CREDIT CARD 3333 PAYMENT *//",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
			primary: "LOAN_PAYMENTS",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png",
		transaction_code: null,
		transaction_id: "PxaqKrXj6eCAM3ympNVJIxpZar5Z5VFoVjdq9",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 5.4,
		authorized_date: "2024-11-19",
		authorized_datetime: null,
		category: ["Travel", "Taxi"],
		category_id: "22016000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/uber_1060.png",
				name: "Uber",
				phone_number: null,
				type: "merchant",
				website: "uber.com",
			},
		],
		date: "2024-11-20",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
		merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
		merchant_name: "Uber",
		name: "Uber 063015 SF**POOL**",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
			primary: "TRANSPORTATION",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
		transaction_code: null,
		transaction_id: "BMnQpwdvAlTRyjDbdlwKUjEPqWLPLwt4VayD9",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "uber.com",
	},
	{
		account_id: "yXQj4dzDy3C53BwA7xqgsx7jLZN4KWu461ppo",
		account_owner: null,
		amount: 5850,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Transfer", "Debit"],
		category_id: "21006000",
		check_number: null,
		counterparties: [],
		date: "2024-11-19",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "ACH Electronic CreditGUSTO PAY 123456",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: "ACH",
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
			primary: "GENERAL_SERVICES",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_SERVICES.png",
		transaction_code: null,
		transaction_id: "oG3rlbNWQXIaBk879V1ohy65XVZ5ZJHoGA96e",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "bGA1LpQwr3IzBQVJZxbaS45Mw7EazVumb9rr3",
		account_owner: null,
		amount: 1000,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Transfer", "Deposit"],
		category_id: "21007000",
		check_number: null,
		counterparties: [],
		date: "2024-11-19",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "CD DEPOSIT .INITIAL.",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "eGkog6Qy3aIXdPVDl1ayCo5mb6qmqjfrePDA5",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 78.5,
		authorized_date: "2024-11-17",
		authorized_datetime: null,
		category: ["Recreation", "Gyms and Fitness Centers"],
		category_id: "17018000",
		check_number: null,
		counterparties: [],
		date: "2024-11-18",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Touchstone Climbing",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
			primary: "PERSONAL_CARE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_PERSONAL_CARE.png",
		transaction_code: null,
		transaction_id: "Qd4Krzg76VfkAxX6rNldSyxVl4DVDbHwRBobe",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: -500,
		authorized_date: "2024-11-18",
		authorized_datetime: null,
		category: ["Travel", "Airlines and Aviation Services"],
		category_id: "22001000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
				name: "United Airlines",
				phone_number: null,
				type: "merchant",
				website: "united.com",
			},
		],
		date: "2024-11-18",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url:
			"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
		merchant_entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
		merchant_name: "United Airlines",
		name: "United Airlines",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRAVEL_FLIGHTS",
			primary: "TRAVEL",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRAVEL.png",
		transaction_code: null,
		transaction_id: "3r7q3PwLoBF9413qDyjmUaV57yQ5QdUZ5XJdd",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "united.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 12,
		authorized_date: "2024-11-17",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Fast Food"],
		category_id: "13005032",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/mcdonalds_619.png",
				name: "McDonald's",
				phone_number: null,
				type: "merchant",
				website: "mcdonalds.com",
			},
		],
		date: "2024-11-17",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: "3322",
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/mcdonalds_619.png",
		merchant_entity_id: "vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22",
		merchant_name: "McDonald's",
		name: "McDonald's",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_FAST_FOOD",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "xGePaxwRyBIgLzZ7G3yjI56wApWwWQu6Lgwdr",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "mcdonalds.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 4.33,
		authorized_date: "2024-11-17",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Coffee Shop"],
		category_id: "13005043",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/starbucks_956.png",
				name: "Starbucks",
				phone_number: null,
				type: "merchant",
				website: "starbucks.com",
			},
		],
		date: "2024-11-17",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/starbucks_956.png",
		merchant_entity_id: "NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb",
		merchant_name: "Starbucks",
		name: "Starbucks",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_COFFEE",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "dknpogaNBdIMxlV9KDe8SkoLXpwLwaFJr9NLg",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "starbucks.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 89.4,
		authorized_date: "2024-11-15",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants"],
		category_id: "13005000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "LOW",
				entity_id: null,
				logo_url: null,
				name: "FUN",
				phone_number: null,
				type: "merchant",
				website: null,
			},
		],
		date: "2024-11-16",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: "FUN",
		name: "SparkFun",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed:
				"ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
			primary: "ENTERTAINMENT",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png",
		transaction_code: null,
		transaction_id: "a8WM1kyPKdFkzdVgpy4eS3DzVaJzJbUZVn4yg",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "nGkKy41bepIEz8v7X3Axho6QnbV5pDHAl7ggK",
		account_owner: null,
		amount: -4.22,
		authorized_date: "2024-11-15",
		authorized_datetime: null,
		category: ["Transfer", "Payroll"],
		category_id: "21009000",
		check_number: null,
		counterparties: [],
		date: "2024-11-15",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "INTRST PYMNT",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "INCOME_WAGES",
			primary: "INCOME",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_INCOME.png",
		transaction_code: null,
		transaction_id: "j9qAGpXkNZF6D7vn1VP5FkA9e8m9m3F6l94n8",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Travel", "Airlines and Aviation Services"],
		category_id: "22001000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
				name: "United Airlines",
				phone_number: null,
				type: "merchant",
				website: "united.com",
			},
		],
		date: "2024-11-05",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url:
			"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
		merchant_entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
		merchant_name: "United Airlines",
		name: "United Airlines",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRAVEL_FLIGHTS",
			primary: "TRAVEL",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRAVEL.png",
		transaction_code: null,
		transaction_id: "ZZ1NPbDp6gugAQVZp3P1IZza51papXCe9WLZG",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "united.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 6.33,
		authorized_date: "2024-11-02",
		authorized_datetime: null,
		category: ["Travel", "Taxi"],
		category_id: "22016000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/uber_1060.png",
				name: "Uber",
				phone_number: null,
				type: "merchant",
				website: "uber.com",
			},
		],
		date: "2024-11-03",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
		merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
		merchant_name: "Uber",
		name: "Uber 072515 SF**POOL**",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
			primary: "TRANSPORTATION",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
		transaction_code: null,
		transaction_id: "4zeKx6jpDvcgNoXKdM9xI4veqyWeWncJ4W5GX",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "uber.com",
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants"],
		category_id: "13005000",
		check_number: null,
		counterparties: [],
		date: "2024-10-31",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Tectra Inc",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed:
				"ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
			primary: "ENTERTAINMENT",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png",
		transaction_code: null,
		transaction_id: "Mz3AylGR6wcKNrwXzPD6TEpzAj8z8DSLGkxaR",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 2078.5,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Payment"],
		category_id: "16000000",
		check_number: null,
		counterparties: [],
		date: "2024-10-30",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "AUTOMATIC PAYMENT - THANK",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "pyxzqgplZLSv3k8mgQDecnV6pBL6L9tp8egPo",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Fast Food"],
		category_id: "13005032",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
				logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
				name: "KFC",
				phone_number: null,
				type: "merchant",
				website: "kfc.com",
			},
		],
		date: "2024-10-30",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
		merchant_entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
		merchant_name: "KFC",
		name: "KFC",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_FAST_FOOD",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "LrBWmMyQ6jFAMKG6XP9DIxK1rRg1g9FkdB8ZK",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "kfc.com",
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Shops", "Sporting Goods"],
		category_id: "19046000",
		check_number: null,
		counterparties: [],
		date: "2024-10-30",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Madison Bicycle Shop",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_SPORTING_GOODS",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "1qkGzJ3L5yuVXozN6BkdUwWx3Egxg1UpEV769",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "nGkKy41bepIEz8v7X3Axho6QnbV5pDHAl7ggK",
		account_owner: null,
		amount: 25,
		authorized_date: "2024-10-20",
		authorized_datetime: null,
		category: ["Payment", "Credit Card"],
		category_id: "16001000",
		check_number: null,
		counterparties: [],
		date: "2024-10-21",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "CREDIT CARD 3333 PAYMENT *//",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
			primary: "LOAN_PAYMENTS",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png",
		transaction_code: null,
		transaction_id: "7xMB4P3LmQCe7A4noGdZsGBWAk8W8vcdr3QDL",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 5.4,
		authorized_date: "2024-10-20",
		authorized_datetime: null,
		category: ["Travel", "Taxi"],
		category_id: "22016000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/uber_1060.png",
				name: "Uber",
				phone_number: null,
				type: "merchant",
				website: "uber.com",
			},
		],
		date: "2024-10-21",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
		merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
		merchant_name: "Uber",
		name: "Uber 063015 SF**POOL**",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
			primary: "TRANSPORTATION",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
		transaction_code: null,
		transaction_id: "NBxGlqbM6wt3PzbJEN6KUGp3ag5356cykaZR9",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "uber.com",
	},
	{
		account_id: "yXQj4dzDy3C53BwA7xqgsx7jLZN4KWu461ppo",
		account_owner: null,
		amount: 5850,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Transfer", "Debit"],
		category_id: "21006000",
		check_number: null,
		counterparties: [],
		date: "2024-10-20",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "ACH Electronic CreditGUSTO PAY 123456",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: "ACH",
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
			primary: "GENERAL_SERVICES",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_SERVICES.png",
		transaction_code: null,
		transaction_id: "AZGeL1b46Qub7AlM5q41fZWZQNmrPwu9azrMq",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "bGA1LpQwr3IzBQVJZxbaS45Mw7EazVumb9rr3",
		account_owner: null,
		amount: 1000,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Transfer", "Deposit"],
		category_id: "21007000",
		check_number: null,
		counterparties: [],
		date: "2024-10-20",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "CD DEPOSIT .INITIAL.",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "FOOD_AND_DRINK_COFFEE",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "3r7q3PwLoBF9413qDyjmUaVaJzgBN4tZQzlXJ",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 78.5,
		authorized_date: "2024-10-18",
		authorized_datetime: null,
		category: ["Recreation", "Gyms and Fitness Centers"],
		category_id: "17018000",
		check_number: null,
		counterparties: [],
		date: "2024-10-19",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Touchstone Climbing",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
			primary: "PERSONAL_CARE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_PERSONAL_CARE.png",
		transaction_code: null,
		transaction_id: "7xMB4P3LmQCe7A4noGdZsGBGamyDKrid6eJ3d",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: -500,
		authorized_date: "2024-10-19",
		authorized_datetime: null,
		category: ["Travel", "Airlines and Aviation Services"],
		category_id: "22001000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
				name: "United Airlines",
				phone_number: null,
				type: "merchant",
				website: "united.com",
			},
		],
		date: "2024-10-19",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url:
			"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
		merchant_entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
		merchant_name: "United Airlines",
		name: "United Airlines",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRAVEL_FLIGHTS",
			primary: "TRAVEL",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRAVEL.png",
		transaction_code: null,
		transaction_id: "qGdBKlpqMXIGxov7AQ6yHM6MENnGwzIgLnrx9",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "united.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 12,
		authorized_date: "2024-10-18",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Fast Food"],
		category_id: "13005032",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/mcdonalds_619.png",
				name: "McDonald's",
				phone_number: null,
				type: "merchant",
				website: "mcdonalds.com",
			},
		],
		date: "2024-10-18",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: "3322",
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/mcdonalds_619.png",
		merchant_entity_id: "vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22",
		merchant_name: "McDonald's",
		name: "McDonald's",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_FAST_FOOD",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "KKzEbR9y6audyqVo6PWmhzkz6MQew8cRKMpJM",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "mcdonalds.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 4.33,
		authorized_date: "2024-10-18",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Coffee Shop"],
		category_id: "13005043",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/starbucks_956.png",
				name: "Starbucks",
				phone_number: null,
				type: "merchant",
				website: "starbucks.com",
			},
		],
		date: "2024-10-18",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/starbucks_956.png",
		merchant_entity_id: "NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb",
		merchant_name: "Starbucks",
		name: "Starbucks",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_COFFEE",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "rGa3rqyK1RI5dZV6Dlm1sMzMQaZ9NeI7pEJmn",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "starbucks.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 89.4,
		authorized_date: "2024-10-16",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants"],
		category_id: "13005000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "LOW",
				entity_id: null,
				logo_url: null,
				name: "FUN",
				phone_number: null,
				type: "merchant",
				website: null,
			},
		],
		date: "2024-10-17",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: "FUN",
		name: "SparkFun",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "zGZ7NJxAVMIAxyQ57RLnImjm9a7d35FlMpNj1",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "nGkKy41bepIEz8v7X3Axho6QnbV5pDHAl7ggK",
		account_owner: null,
		amount: -4.22,
		authorized_date: "2024-10-16",
		authorized_datetime: null,
		category: ["Transfer", "Payroll"],
		category_id: "21009000",
		check_number: null,
		counterparties: [],
		date: "2024-10-16",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "INTRST PYMNT",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "INCOME_WAGES",
			primary: "INCOME",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_INCOME.png",
		transaction_code: null,
		transaction_id: "Qd4Krzg76VfkAxX6rNldSyxy3v7GmocwZvmB8",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Travel", "Airlines and Aviation Services"],
		category_id: "22001000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
				name: "United Airlines",
				phone_number: null,
				type: "merchant",
				website: "united.com",
			},
		],
		date: "2024-10-06",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url:
			"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
		merchant_entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
		merchant_name: "United Airlines",
		name: "United Airlines",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRAVEL_FLIGHTS",
			primary: "TRAVEL",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRAVEL.png",
		transaction_code: null,
		transaction_id: "eGkog6Qy3aIXdPVDl1ayCo5or7ZBM3SrJp9Pa",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "united.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 6.33,
		authorized_date: "2024-10-03",
		authorized_datetime: null,
		category: ["Travel", "Taxi"],
		category_id: "22016000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/uber_1060.png",
				name: "Uber",
				phone_number: null,
				type: "merchant",
				website: "uber.com",
			},
		],
		date: "2024-10-04",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
		merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
		merchant_name: "Uber",
		name: "Uber 072515 SF**POOL**",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
			primary: "TRANSPORTATION",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
		transaction_code: null,
		transaction_id: "BMnQpwdvAlTRyjDbdlwKUjEjbDlxZJf4XrMan",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "uber.com",
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants"],
		category_id: "13005000",
		check_number: null,
		counterparties: [],
		date: "2024-10-01",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Tectra Inc",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed:
				"ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
			primary: "ENTERTAINMENT",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png",
		transaction_code: null,
		transaction_id: "Qd4Krzg76VfkAxX6rNldSyxy3v7GmocwZvmB3",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 2078.5,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Payment"],
		category_id: "16000000",
		check_number: null,
		counterparties: [],
		date: "2024-09-30",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "AUTOMATIC PAYMENT - THANK",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "1qkGzJ3L5yuVXozN6BkdUwWwAdL4ZjHpNBjVN",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Fast Food"],
		category_id: "13005032",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
				logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
				name: "KFC",
				phone_number: null,
				type: "merchant",
				website: "kfc.com",
			},
		],
		date: "2024-09-30",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
		merchant_entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
		merchant_name: "KFC",
		name: "KFC",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_FAST_FOOD",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "Mz3AylGR6wcKNrwXzPD6TEpEyKr3GxFLNq6kz",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "kfc.com",
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Shops", "Sporting Goods"],
		category_id: "19046000",
		check_number: null,
		counterparties: [],
		date: "2024-09-30",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Madison Bicycle Shop",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_SPORTING_GOODS",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "ZZ1NPbDp6gugAQVZp3P1IZzZdrJMGLueP4qWb",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "nGkKy41bepIEz8v7X3Axho6QnbV5pDHAl7ggK",
		account_owner: null,
		amount: 25,
		authorized_date: "2024-09-20",
		authorized_datetime: null,
		category: ["Payment", "Credit Card"],
		category_id: "16001000",
		check_number: null,
		counterparties: [],
		date: "2024-09-21",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "CREDIT CARD 3333 PAYMENT *//",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
			primary: "LOAN_PAYMENTS",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png",
		transaction_code: null,
		transaction_id: "ZZ1NPbDp6gugAQVZp3P1IZzZdrJMGLueP4qW5",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 5.4,
		authorized_date: "2024-09-20",
		authorized_datetime: null,
		category: ["Travel", "Taxi"],
		category_id: "22016000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/uber_1060.png",
				name: "Uber",
				phone_number: null,
				type: "merchant",
				website: "uber.com",
			},
		],
		date: "2024-09-21",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
		merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
		merchant_name: "Uber",
		name: "Uber 063015 SF**POOL**",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
			primary: "TRANSPORTATION",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
		transaction_code: null,
		transaction_id: "3r7q3PwLoBF9413qDyjmUaVaJzgBN4tZQzlXn",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "uber.com",
	},
	{
		account_id: "yXQj4dzDy3C53BwA7xqgsx7jLZN4KWu461ppo",
		account_owner: null,
		amount: 5850,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Transfer", "Debit"],
		category_id: "21006000",
		check_number: null,
		counterparties: [],
		date: "2024-09-20",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "ACH Electronic CreditGUSTO PAY 123456",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: "ACH",
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
			primary: "GENERAL_SERVICES",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_SERVICES.png",
		transaction_code: null,
		transaction_id: "GglpWwBRA3CwQMdpzoVNswAw35d76aH6qkMwE",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "bGA1LpQwr3IzBQVJZxbaS45Mw7EazVumb9rr3",
		account_owner: null,
		amount: 1000,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Transfer", "Deposit"],
		category_id: "21007000",
		check_number: null,
		counterparties: [],
		date: "2024-09-20",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "CD DEPOSIT .INITIAL.",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "xGePaxwRyBIgLzZ7G3yjI565nJqxr3i6k84gj",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 78.5,
		authorized_date: "2024-09-18",
		authorized_datetime: null,
		category: ["Recreation", "Gyms and Fitness Centers"],
		category_id: "17018000",
		check_number: null,
		counterparties: [],
		date: "2024-09-19",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Touchstone Climbing",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
			primary: "PERSONAL_CARE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_PERSONAL_CARE.png",
		transaction_code: null,
		transaction_id: "LrBWmMyQ6jFAMKG6XP9DIxKxay57j8ikqwjB3",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: -500,
		authorized_date: "2024-09-19",
		authorized_datetime: null,
		category: ["Travel", "Airlines and Aviation Services"],
		category_id: "22001000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
				name: "United Airlines",
				phone_number: null,
				type: "merchant",
				website: "united.com",
			},
		],
		date: "2024-09-19",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url:
			"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
		merchant_entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
		merchant_name: "United Airlines",
		name: "United Airlines",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRAVEL_FLIGHTS",
			primary: "TRAVEL",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRAVEL.png",
		transaction_code: null,
		transaction_id: "xGePaxwRyBIgLzZ7G3yjI565nJqxr3i6k84gB",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "united.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 12,
		authorized_date: "2024-09-18",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Fast Food"],
		category_id: "13005032",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/mcdonalds_619.png",
				name: "McDonald's",
				phone_number: null,
				type: "merchant",
				website: "mcdonalds.com",
			},
		],
		date: "2024-09-18",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: "3322",
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/mcdonalds_619.png",
		merchant_entity_id: "vzWXDWBjB06j5BJoD3Jo84OJZg7JJzmqOZA22",
		merchant_name: "McDonald's",
		name: "McDonald's",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_FAST_FOOD",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "dknpogaNBdIMxlV9KDe8SkokGD1xJMcJl7E9R",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "mcdonalds.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 4.33,
		authorized_date: "2024-09-18",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Coffee Shop"],
		category_id: "13005043",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/starbucks_956.png",
				name: "Starbucks",
				phone_number: null,
				type: "merchant",
				website: "starbucks.com",
			},
		],
		date: "2024-09-18",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/starbucks_956.png",
		merchant_entity_id: "NZAJQ5wYdo1W1p39X5q5gpb15OMe39pj4pJBb",
		merchant_name: "Starbucks",
		name: "Starbucks",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_COFFEE",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "a8WM1kyPKdFkzdVgpy4eS3D3d1myw5TZor5nK",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "starbucks.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 89.4,
		authorized_date: "2024-09-16",
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants"],
		category_id: "13005000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "LOW",
				entity_id: null,
				logo_url: null,
				name: "FUN",
				phone_number: null,
				type: "merchant",
				website: null,
			},
		],
		date: "2024-09-17",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: "FUN",
		name: "SparkFun",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed:
				"ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
			primary: "ENTERTAINMENT",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png",
		transaction_code: null,
		transaction_id: "4zeKx6jpDvcgNoXKdM9xI4v4EBGaLRfJ9BbWp",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "nGkKy41bepIEz8v7X3Axho6QnbV5pDHAl7ggK",
		account_owner: null,
		amount: -4.22,
		authorized_date: "2024-09-16",
		authorized_datetime: null,
		category: ["Transfer", "Payroll"],
		category_id: "21009000",
		check_number: null,
		counterparties: [],
		date: "2024-09-16",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "INTRST PYMNT",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "INCOME_WAGES",
			primary: "INCOME",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_INCOME.png",
		transaction_code: null,
		transaction_id: "rGa3rqyK1RI5dZV6Dlm1sMzMQaZ9NeI7pEJmQ",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Travel", "Airlines and Aviation Services"],
		category_id: "22001000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
				name: "United Airlines",
				phone_number: null,
				type: "merchant",
				website: "united.com",
			},
		],
		date: "2024-09-06",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url:
			"https://plaid-merchant-logos.plaid.com/united_airlines_1065.png",
		merchant_entity_id: "NKDjqyAdQQzpyeD8qpLnX0D6yvLe2KYKYYzQ4",
		merchant_name: "United Airlines",
		name: "United Airlines",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRAVEL_FLIGHTS",
			primary: "TRAVEL",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRAVEL.png",
		transaction_code: null,
		transaction_id: "pyxzqgplZLSv3k8mgQDecnVnyEWGaZipbaoee",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "united.com",
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 6.33,
		authorized_date: "2024-09-03",
		authorized_datetime: null,
		category: ["Travel", "Taxi"],
		category_id: "22016000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/uber_1060.png",
				name: "Uber",
				phone_number: null,
				type: "merchant",
				website: "uber.com",
			},
		],
		date: "2024-09-04",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
		merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
		merchant_name: "Uber",
		name: "Uber 072515 SF**POOL**",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
			primary: "TRANSPORTATION",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
		transaction_code: null,
		transaction_id: "NBxGlqbM6wt3PzbJEN6KUGpGkEw9RZiyo96ap",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "uber.com",
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants"],
		category_id: "13005000",
		check_number: null,
		counterparties: [],
		date: "2024-09-01",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Tectra Inc",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed:
				"ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
			primary: "ENTERTAINMENT",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png",
		transaction_code: null,
		transaction_id: "oG3rlbNWQXIaBk879V1ohy6yjkE3xdco1EqAG",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 2078.5,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Payment"],
		category_id: "16000000",
		check_number: null,
		counterparties: [],
		date: "2024-08-31",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "AUTOMATIC PAYMENT - THANK",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "Epy187EnbNFvNGaM7zVKcPWPaxNkABc4rbxza",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Food and Drink", "Restaurants", "Fast Food"],
		category_id: "13005032",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
				logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
				name: "KFC",
				phone_number: null,
				type: "merchant",
				website: "kfc.com",
			},
		],
		date: "2024-08-31",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/kfc_546.png",
		merchant_entity_id: "3LmdknrdwVy9vm0dqj417rLKeJXW7veV7eb2e",
		merchant_name: "KFC",
		name: "KFC",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "FOOD_AND_DRINK_FAST_FOOD",
			primary: "FOOD_AND_DRINK",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png",
		transaction_code: null,
		transaction_id: "8d13N6VvAwfEGrN5LmnRhynybqBMVJcWgq354",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: "kfc.com",
	},
	{
		account_id: "mGzqmJZa7LI7k6vwZQXBh1oJPEprWVhgyK88P",
		account_owner: null,
		amount: 500,
		authorized_date: null,
		authorized_datetime: null,
		category: ["Shops", "Sporting Goods"],
		category_id: "19046000",
		check_number: null,
		counterparties: [],
		date: "2024-08-31",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "Madison Bicycle Shop",
		payment_channel: "in store",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "GENERAL_MERCHANDISE_SPORTING_GOODS",
			primary: "GENERAL_MERCHANDISE",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_GENERAL_MERCHANDISE.png",
		transaction_code: null,
		transaction_id: "gGy8EpZNdAIm4NV6ypbahBnBG4pW7oCEPW89k",
		transaction_type: "place",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "nGkKy41bepIEz8v7X3Axho6QnbV5pDHAl7ggK",
		account_owner: null,
		amount: 25,
		authorized_date: "2024-08-21",
		authorized_datetime: null,
		category: ["Payment", "Credit Card"],
		category_id: "16001000",
		check_number: null,
		counterparties: [],
		date: "2024-08-22",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: null,
		merchant_entity_id: null,
		merchant_name: null,
		name: "CREDIT CARD 3333 PAYMENT *//",
		payment_channel: "other",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "LOW",
			detailed: "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
			primary: "LOAN_PAYMENTS",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png",
		transaction_code: null,
		transaction_id: "zGZ7NJxAVMIAxyQ57RLnImjm9a7d35FlMpNjy",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: null,
	},
	{
		account_id: "GglpWwBRA3CwQMdpzoVNswAkp79Erqh6MNRRG",
		account_owner: null,
		amount: 5.4,
		authorized_date: "2024-08-21",
		authorized_datetime: null,
		category: ["Travel", "Taxi"],
		category_id: "22016000",
		check_number: null,
		counterparties: [
			{
				confidence_level: "VERY_HIGH",
				entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
				logo_url:
					"https://plaid-merchant-logos.plaid.com/uber_1060.png",
				name: "Uber",
				phone_number: null,
				type: "merchant",
				website: "uber.com",
			},
		],
		date: "2024-08-22",
		datetime: null,
		iso_currency_code: "USD",
		location: {
			address: null,
			city: null,
			country: null,
			lat: null,
			lon: null,
			postal_code: null,
			region: null,
			store_number: null,
		},
		logo_url: "https://plaid-merchant-logos.plaid.com/uber_1060.png",
		merchant_entity_id: "eyg8o776k0QmNgVpAmaQj4WgzW9Qzo6O51gdd",
		merchant_name: "Uber",
		name: "Uber 063015 SF**POOL**",
		payment_channel: "online",
		payment_meta: {
			by_order_of: null,
			payee: null,
			payer: null,
			payment_method: null,
			payment_processor: null,
			ppd_id: null,
			reason: null,
			reference_number: null,
		},
		pending: false,
		pending_transaction_id: null,
		personal_finance_category: {
			confidence_level: "VERY_HIGH",
			detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
			primary: "TRANSPORTATION",
		},
		personal_finance_category_icon_url:
			"https://plaid-category-icons.plaid.com/PFC_TRANSPORTATION.png",
		transaction_code: null,
		transaction_id: "PxaqKrXj6eCAM3ympNVJIxpxvRgeQdio8g6j6",
		transaction_type: "special",
		unofficial_currency_code: null,
		website: "uber.com",
	},
];

const CONSTANT_CHIP_COLOR_PALLET = [
	"bg-blue-100 text-blue-800",
	"bg-green-100 text-green-800",
	"bg-yellow-100 text-yellow-800",
	"bg-red-100 text-red-800",
	"bg-indigo-100 text-indigo-800",
	"bg-purple-100 text-purple-800",
	"bg-pink-100 text-pink-800",
	"bg-teal-100 text-teal-800",
	"bg-orange-100 text-orange-800",
	"bg-cyan-100 text-cyan-800",
	"bg-lime-100 text-lime-800",
	"bg-amber-100 text-amber-800",
	"bg-emerald-100 text-emerald-800",
	"bg-fuchsia-100 text-fuchsia-800",
	"bg-rose-100 text-rose-800",
	"bg-sky-100 text-sky-800",
];

// Create a mapping of categories to colors, cycling through the color palette
const getCategoryColorMap = (transactions: any[]) => {
	const categories: string[] = [
		...new Set(transactions.flatMap((t: any) => t.category)),
	]; // Get unique categories
	
	// FIXME: need optimization (instead of reiterating over categories for color, filtering think to store it....)
	return categories.reduce(
		(map: Record<string, string>, category: string, index: number) => {
			map[category] =
				CONSTANT_CHIP_COLOR_PALLET[
				index % CONSTANT_CHIP_COLOR_PALLET.length
				]; // Assign colors in a loop
			return map;
		},
		{} as Record<string, string>
	);
};

export default function Transactions() {
	const [isOpen, setIsOpen] = useState(false);
	const [filteredTransactions, setFilteredTransactions] =
		useState(sampleTransactions);
	const [filter, setFilter] = useState({
		type: "all",
		categories: [],
		sortByDate: "asc",
	});
	const [selectedCategories, setSelectedCategories] = useState<string[]>([]);

	// Get category-color mapping
	const categoryColorMap = getCategoryColorMap(filteredTransactions);

	// Handle filter changes
	const handleFilterChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
		const { name, value } = e.target;
		setFilter((prevFilter) => ({ ...prevFilter, [name]: value }));
	};

	// Handle category selection
	const handleCategorySelection = (category: string) => {
		const updatedCategories = selectedCategories.includes(category)
			? selectedCategories.filter((cat) => cat !== category)
			: [...selectedCategories, category];
		setSelectedCategories(updatedCategories);
	};

	// Filter and sort transactions based on current state
	const applyFiltersAndSort = () => {
		let filteredData = [...sampleTransactions];

		// Filter by credit/debit
		if (filter.type !== "all") {
			filteredData = filteredData.filter((t) =>
				filter.type === "credit" ? t.amount > 0 : t.amount < 0
			);
		}

		// Filter by selected categories
		if (selectedCategories.length > 0) {
			filteredData = filteredData.filter((t) =>
				t.category.some((cat) => selectedCategories.includes(cat))
			);
		}

		// Sort by date
		filteredData.sort((a, b) => {
			const dateA = new Date(a.date).getTime();
			const dateB = new Date(b.date).getTime();
			return filter.sortByDate === "asc" ? dateA - dateB : dateB - dateA;
		});

		setFilteredTransactions(filteredData);
	};

	const toggleCategorySelection = (category: string) => {
		setSelectedCategories((prevSelectedCategories) => {
			if (prevSelectedCategories.includes(category)) {
				return prevSelectedCategories.filter(
					(item) => item !== category
				); // Deselect category
			} else {
				return [...prevSelectedCategories, category]; // Select category
			}
		});
	};

	useEffect(() => {
		applyFiltersAndSort();
	}, [filter, selectedCategories]);

	return (
		<div className="bg-gray-50 min-h-screen">
			<div className="pt-10">
				<section className="container mx-auto px-6 py-16 flex flex-col items-center">
					<h1 className="text-5xl font-bold text-gray-900 mb-4">
						Transactions
					</h1>
					{/* Filters */}
					<div className="mb-6 flex space-x-4">
						<select
							name="type"
							value={filter.type}
							onChange={handleFilterChange}
							className="p-2 border rounded"
						>
							<option value="all">All</option>
							<option value="credit">Credit</option>
							<option value="debit">Debit</option>
						</select>

						<select
							name="sortByDate"
							value={filter.sortByDate}
							onChange={handleFilterChange}
							className="p-2 border rounded"
						>
							<option value="asc">Date Ascending</option>
							<option value="desc">Date Descending</option>
						</select>

						<div className="space-x-2">
							<span>Filter by Category:</span>
							
							{Object.keys(categoryColorMap).map((category) => (
								<button
									key={category}
									onClick={() =>
										handleCategorySelection(category)
									}
									className={`px-3 py-1 rounded ${selectedCategories.includes(category)
											? "bg-blue-200 text-blue-800"
											: "bg-gray-200 text-gray-800"
										}`}
								>
									{category}
								</button>
							))}
						</div>
					</div>

					<div className="w-full overflow-x-auto">
						<table className="min-w-full border border-gray-300 bg-white rounded-lg shadow-md">
							<thead>
								<tr className="bg-gray-100 border-b">
									<th className="px-1 py-2 text-left text-gray-600 font-semibold">
										{" "}
									</th>
									<th className="px-4 py-2 text-left text-gray-600 font-semibold">
										Transaction Name
									</th>
									<th className="px-4 py-2 text-left text-gray-600 font-semibold">
										Amount
									</th>
									<th className="px-4 py-2 text-left text-gray-600 font-semibold">
										Type
									</th>
									<th className="px-4 py-2 text-left text-gray-600 font-semibold">
										Date
									</th>
									<th className="px-4 py-2 text-left text-gray-600 font-semibold">
										Categories
									</th>
								</tr>
							</thead>
							<tbody>
								{filteredTransactions.map((transaction) => (
									<tr
										key={transaction.transaction_id}
										className={`border-b hover:bg-gray-50 ${transaction.amount < 0
												? "text-red-600"
												: "text-green-600"
											}`}
									>
										<td className="px-4 py-2">
											<img
												src={
													transaction.logo_url || transaction.personal_finance_category_icon_url ||
													"/default-logo.png"
												}
												alt="Logo"
												className="w-6 h-6 rounded-full"
											/>
										</td>
										<td className="px-4 py-2">
											{transaction.name}
										</td>
										<td className="px-4 py-2">
											${transaction.amount.toFixed(2)}
										</td>
										<td className="px-4 py-2">
											{transaction.transaction_type}
										</td>
										<td className="px-4 py-2">
											{transaction.date}
										</td>
										<td className="px-4 py-2">
											{transaction.category.map(
												(cat, index) => (
													<span
														key={index}
														className={`inline-flex items-center px-3 py-1 mr-2 text-sm font-medium rounded-full ${categoryColorMap[cat]}`}
													>
														{cat}
													</span>
												)
											)}
										</td>
									</tr>
								))}
							</tbody>
						</table>
					</div>
				</section>
			</div>
		</div>
	);
}
